<script>
  import Button from "../buttons/Button.svelte";
  import {getContext} from "svelte";
  import ChangeLogModal from "./ChangeLogModal.svelte";
  import Changelog from "./Changelog";
  import colorLookup, {modalOptions} from "../colors";

  const {open} = getContext("simple-modal");

  function openChangelog(){
    open(ChangeLogModal, {}, modalOptions);
  }
</script>

<style>
  .container {
    display: flex;
    flex-direction: column;
    padding: 12px;
  }

  h1 {
    margin: 0;
    text-align: center;
  }
</style>
<div class="container" style={"color: " + colorLookup.textDark}>
  <h1 style={"color: " + colorLookup.text}>About</h1>
  <Button on:click={() => window.open("https://openai.com/blog/musenet")}>Music generated by MuseNet</Button>
  <Button on:click={() => window.open("https://github.com/stevenwaterman/musetree")}>Source Code on GitHub</Button>
  <Button on:click={() => window.open("http://www.stevenwaterman.uk")}>Developed by Steven Waterman</Button>
  <Button on:click={openChangelog}>v{Changelog[0].version.join(".")}</Button>
</div>
